# Site settings
title: 404 Order Not Found
header-img: img/home-bg.png
email: cannon.herbert@yahoo.com
copyright_name: cannonherbert
description: > # this means to ignore newlines until "baseurl:"
  From Hoagies to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cannonherbert
learn_profile: cannonherbert
email_username: cannon.herbert@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
